name: demo-pipeline
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - openjdk=11
  - pip
  - jupyter
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - pip:
      - pyspark
      - delta-spark